AWSTemplateFormatVersion: 2010-09-09
Description: lecture10_vpc_setting

Parameters: 
  NameBase:
    Description: this is base name.
    Type: String
    Default: lecture10
  AZa:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ap-northeast-1a
  AZc:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ap-northeast-1c

Resources:
# ------------------------------------------------------------#
#  VPC
# ------------------------------------------------------------#
  lecture10VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      InstanceTenancy: default
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: name
          Value: !Sub ${NameBase}-vpc

# ------------------------------------------------------------#
#  Subnet
# ------------------------------------------------------------#
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZa
      VpcId: !Ref lecture10VPC
      CidrBlock: 10.0.0.0/20
      Tags:
        - Key: name
          Value: !Sub ${NameBase}-subnet-public1-${AZa}

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZc
      VpcId: !Ref lecture10VPC
      CidrBlock: 10.0.16.0/20
      Tags:
        - Key: name
          Value: !Sub ${NameBase}-subnet-public2-${AZc}


  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZa
      VpcId: !Ref lecture10VPC
      CidrBlock: 10.0.128.0/20
      Tags:
        - Key: name
          Value: !Sub ${NameBase}-subnet-private1-${AZa}


  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZc
      VpcId: !Ref lecture10VPC
      CidrBlock: 10.0.144.0/20
      Tags:
        - Key: name
          Value: !Sub ${NameBase}-subnet-private2-${AZc}
# ------------------------------------------------------------#
#  InternetGateway
# ------------------------------------------------------------#
  lecture10VPCIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: name
          Value:  !Sub ${NameBase}-igw
  lecture10VPCAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref lecture10VPC
      InternetGatewayId: !Ref lecture10VPCIGW

# ------------------------------------------------------------#
#  RouteTable
# ------------------------------------------------------------#
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref lecture10VPC
      Tags:
        - Key: name
          Value: !Sub ${NameBase}-rtb-public

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref lecture10VPCIGW

  PublicSubnet1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref lecture10VPC
      Tags:
        - Key: name
          Value: !Sub ${NameBase}-rtb-private1-${AZa}
  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref lecture10VPC
      Tags:
        - Key: name
          Value: !Sub ${NameBase}-rtb-private1-${AZc}
  PrivateSubnet1Associatio:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable1

  PrivateSubnet2Associatio:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable2

Outputs:
  VPCID:
    Description: information about VPCID
    Value: !Ref lecture10VPC
    Export: 
      Name: !Sub ${AWS::StackName}-VPCID

  PublicSubnet1:
    Description: informarion about publicSubnet1
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub ${AWS::StackName}-PublicSubnet1-a

  PublicSubnet2:
    Description: informarion about publicSubnet2
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub ${AWS::StackName}-PublicSubnet2-c

  PrivateSubnet1:
    Description: informarion about PrivateSubnet1
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub ${AWS::StackName}-PrivateSubnet1-a

  PrivateSubnet2:
    Description: informarion about PrivateSubnet2
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub ${AWS::StackName}-PrivateSubnet2-c
