AWSTemplateFormatVersion: 2010-09-09
Description: lecture10_vpc_setting

Parameters: 
  NameBase:
    Description: this is base name.
    Type: String
    Default: lecture10

Resources:
# ------------------------------------------------------------#
#  VPC
# ------------------------------------------------------------#
  lecture10VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      InstanceTenancy: default
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: keyname
          Value: !Sub vpc-${NameBase}

# ------------------------------------------------------------#
#  Subnet
# ------------------------------------------------------------#
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref lecture10VPC
      CidrBlock: 10.0.0.0/20
      Tags:
        - Key: keyname
          Value: !Sub ${NameBase}-subnet-public1-ap-northeast-1a

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref lecture10VPC
      CidrBlock: 10.0.16.0/20
      Tags:
        - Key: keyname
          Value: !Sub ${NameBase}-subnet-public2-ap-northeast-1c


  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref lecture10VPC
      CidrBlock: 10.0.128.0/20
      Tags:
        - Key: keyname
          Value: !Sub ${NameBase}-subnet-private1-ap-northeast-1a


  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref lecture10VPC
      CidrBlock: 10.0.144.0/20
      Tags:
        - Key: keyname
          Value: !Sub ${NameBase}-subnet-private2-ap-northeast-1c
# ------------------------------------------------------------#
#  InternetGateway
# ------------------------------------------------------------#
  l10VPCIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: keyname
          Value:  !Sub ${NameBase}-igw
  l10VPCAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref lecture10VPC
      InternetGatewayId: !Ref l10VPCIGW

# ------------------------------------------------------------#
#  RouteTable
# ------------------------------------------------------------#
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref lecture10VPC
      Tags:
        - Key: keyname
          Value: !Sub ${NameBase}-rtb-public

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref l10VPCIGW

  PublicSubnet1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref lecture10VPC
      Tags:
        - Key: keyname
          Value: !Sub ${NameBase}-rtb-private1-ap-northeast-1a
  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref lecture10VPC
      Tags:
        - Key: keyname
          Value: !Sub ${NameBase}-rtb-private1-ap-northeast-1c
  PrivateSubnet1Associatio:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable1

  PrivateSubnet2Associatio:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable2

Outputs:
  VPCID:
    Description: information about VPCID
    Value: !Ref lecture10VPC
    Export: 
      Name: !Sub ${AWS::StackName}-VPCID

  PublicSubnet1:
    Description: informarion about publicSubnet1
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub ${AWS::StackName}-PublicSubnet1

  PublicSubnet2:
    Description: informarion about publicSubnet2
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub ${AWS::StackName}-PublicSubnet2

  PrivateSubnet1:
    Description: informarion about PrivateSubnet1
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub ${AWS::StackName}-PrivateSubnet1

  PrivateSubnet2:
    Description: informarion about PrivateSubnet2
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub ${AWS::StackName}-PrivateSubnet2
  