AWSTemplateFormatVersion: 2010-09-09
Description: lecture10_vpc_setting

Parameters: 
  NameBase:
    Description: this is base name.
    Type: String
    Default: lecture10
  AZ1:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ap-northeast-1a
  AZ2:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ap-northeast-1c

Resources:
# ------------------------------------------------------------#
#  VPC
# ------------------------------------------------------------#
  lecture10VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      InstanceTenancy: default
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-vpc

# ------------------------------------------------------------#
#  Subnet
# ------------------------------------------------------------#
  lecture10PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZ1
      VpcId: !Ref lecture10VPC
      CidrBlock: 10.0.0.0/20
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-subnet-public1-${AZ1}

  lecture10PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZ2
      VpcId: !Ref lecture10VPC
      CidrBlock: 10.0.16.0/20
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-subnet-public2-${AZ2}


  lecture10PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZ1
      VpcId: !Ref lecture10VPC
      CidrBlock: 10.0.128.0/20
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-subnet-private1-${AZ1}


  lecture10PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZ2
      VpcId: !Ref lecture10VPC
      CidrBlock: 10.0.144.0/20
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-subnet-private2-${AZ2}
# ------------------------------------------------------------#
#  InternetGateway
# ------------------------------------------------------------#
  lecture10VPCIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value:  !Sub ${NameBase}-igw
  lecture10VPCAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref lecture10VPC
      InternetGatewayId: !Ref lecture10VPCIGW

# ------------------------------------------------------------#
#  RouteTable
# ------------------------------------------------------------#
  lecture10PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref lecture10VPC
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-rtb-public

  lecture10PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref lecture10PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref lecture10VPCIGW

  lecture10PublicSubnet1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref lecture10PublicSubnet1
      RouteTableId: !Ref lecture10PublicRouteTable

  lecture10PublicSubnet2Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref lecture10PublicSubnet2
      RouteTableId: !Ref lecture10PublicRouteTable

  lecture10PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref lecture10VPC
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-rtb-private1-${AZ1}
  lecture10PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref lecture10VPC
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-rtb-private1-${AZ2}
  lecture10PrivateSubnet1Associatio:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref lecture10PrivateSubnet1
      RouteTableId: !Ref lecture10PrivateRouteTable1

  lecture10PrivateSubnet2Associatio:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref lecture10PrivateSubnet2
      RouteTableId: !Ref lecture10PrivateRouteTable2

Outputs:
  lecture10VPCID:
    Description: information about VPCID
    Value: !Ref lecture10VPC
    Export: 
      Name: !Sub ${AWS::StackName}-VPCID

  lecture10PublicSubnet1:
    Description: informarion about publicSubnet1
    Value: !Ref lecture10PublicSubnet1
    Export:
      Name: !Sub ${AWS::StackName}-PublicSubnet1-${AZ1}-ID

  lecture10PublicSubnet2:
    Description: informarion about publicSubnet2
    Value: !Ref lecture10PublicSubnet2
    Export:
      Name: !Sub ${AWS::StackName}-PublicSubnet2-${AZ2}-ID

  lecture10PrivateSubnet1:
    Description: informarion about PrivateSubnet1
    Value: !Ref lecture10PrivateSubnet1
    Export:
      Name: !Sub ${AWS::StackName}-PrivateSubnet1-${AZ1}-ID
  lecture10PrivateSubnet2:
    Description: informarion about PrivateSubnet2
    Value: !Ref lecture10PrivateSubnet2
    Export:
      Name: !Sub ${AWS::StackName}-PrivateSubnet2-${AZ2}-ID
